version: '3.7'

services:
  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    command: server /data
    networks:
      mlserving_example:
        ipv4_address: $MINIO_HOST
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

networks:
  mlserving_example:
    driver: bridge
    ipam:
      config:
        - subnet: 10.200.0.0/24
